### ISSUE TITLE
Service Feature Management problems

### ISSUE THREAD

**Issue by raoulhentschel** [SebLeich/broker-client#18]
The new service management features (e.g. Zertifikate, Datenspeicherorte) are visible but not clickable.
![image](https://user-images.githubusercontent.com/54834712/74035238-3333d100-49ba-11ea-9f1c-7f8694604c6a.png)

**Comment by SebLeich** [comment]
These functions are currently not implemented. We need further enhancements to provide them.

**Comment by SebLeich** [comment]
Duplicate of #13
